# Generated by Django 5.2.5 on 2025-08-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_alter_entryfields_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryfields',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entryfields',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
