# Generated by Django 5.2.5 on 2025-08-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_entryfields_date_paid_alter_entryfields_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryfields',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
