# Generated by Django 5.2.5 on 2025-08-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_alter_entryfields_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryfields',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
